<!-- - - - - -  FOOTER - - - - -->
<footer id="footer">
    <div class="container">
            <!-- ---- bloque de copyright ------------------------------------- -->
            <div class="b-footer-primary">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">Copyright © 2020 - Todos Los Derechos Reservados / SENA - ADSI</div>
                        <div class="col-md-3">
                            <a href="<?php echo Conectar::ruta();?>"><img data-retina class="b-footer-logo color-theme" src="<?php echo Conectar::ruta();?>img/logo-header.png" width="40" height="25"alt="Logo"/></a>
                        </div>
                        <div class="col-md-1">
                            <div class="b-btn f-btn b-btn-default b-right b-footer__btn_up f-footer__btn_up j-footer__btn_up">
                                <i class="fa fa-chevron-up"></i>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <!-- ---- Fin bloque de copyright ------------------------------------- -->
    </footer>