<!-- - - - - -  FOOTER - - - - -->
<footer id="footer">

    <!-- ---- bloque de copyright ------------------------------------- -->
    <div class="b-footer-primary">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-xs-12 f-copyright b-copyright">Copyright © 2020 - Todos Los Derechos Reservados / SENA - ADSI</div>
                <div class="col-sm-8 col-xs-12">
                    <div class="b-btn f-btn b-btn-default b-right b-footer__btn_up f-footer__btn_up j-footer__btn_up">
                        <i class="fa fa-chevron-up"></i>
                    </div>
                    <nav class="b-bottom-nav f-bottom-nav b-right hidden-xs">
                        <ul>
                            <li class="is-active-bottom-nav"><a href="<?php echo Conectar::ruta();?>">inicio</a></li>
                            <li><a href="<?php echo Conectar::ruta();?>c-form-info-forplast/">nosotros</a></li>
                            <li><a href="<?php echo Conectar::ruta();?>c-frm-equipo-desarrollador/">equipo desarrollo</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    
    
    <div class="container">
        <div class="b-footer-secondary row">
    
            <!-- bloque logo footer ---------------------------------- -->
            <div class="col-md-3 col-sm-12 col-xs-12 f-center b-footer-logo-containter bloque">
                <a href="<?php echo Conectar::ruta();?>"><img data-retina class="b-footer-logo color-theme" src="<?php echo Conectar::ruta();?>img/forplast-logo-footer.png" alt="Logo"/></a>

                <div class="b-footer-logo-text f-footer-logo-text">
                <p>Forplast la tienda del motociclista.</p>
                <!-- <div class="b-btn-group-hor f-btn-group-hor">
                <a href="#" class="b-btn-group-hor__item f-btn-group-hor__item">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="#" class="b-btn-group-hor__item f-btn-group-hor__item">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="#" class="b-btn-group-hor__item f-btn-group-hor__item">
                    <i class="fa fa-dribbble"></i>
                </a>
                <a href="#" class="b-btn-group-hor__item f-btn-group-hor__item">
                    <i class="fa fa-behance"></i>
                </a>
                </div> -->
            </div>
            </div>
    
            <!-- bloque informacion ------------------------------------ -->
        
            <div class="col-md-3 col-sm-12 col-xs-12">
            <h4 class="f-primary-b">Otros enlaces</h4>
            <div class="b-blog-short-post row">
                <div class="b-blog-short-post__item col-md-12 col-sm-4 col-xs-12 f-primary-b">
                <div class="b-blog-short-post__item_text f-blog-short-post__item_text">
                    <a href="<?php echo Conectar::ruta();?>c-form-info-forplast/">Forplast - misión y visión</a>
                </div> <br>
                </div>
                <div class="b-blog-short-post__item col-md-12 col-sm-4 col-xs-12 f-primary-b">
                <div class="b-blog-short-post__item_text f-blog-short-post__item_text">
                    <a href="<?php echo Conectar::ruta();?>c-frm-proyecto/">Proyecto formativo</a>
                </div> <br>
                </div>
                <div class="b-blog-short-post__item col-md-12 col-sm-4 col-xs-12 f-primary-b">
                <div class="b-blog-short-post__item_text f-blog-short-post__item_text">
                    <a href="<?php echo Conectar::ruta();?>c-frm-equipo-desarrollador/">Equipo de desarrollo</a>
                </div> <br>
                </div>
            </div>
            </div>
    
            <div class="col-md-3 col-sm-12 col-xs-12">
                <h4 class="f-primary-b">información de contacto</h4>
                <div class="b-contacts-short-item-group">
                <div class="b-contacts-short-item col-md-12 col-sm-4 col-xs-12">
                    <div class="b-contacts-short-item__icon f-contacts-short-item__icon f-contacts-short-item__icon_lg b-left">
                    <i class="fa fa-map-marker"></i>
                    </div>
                    <div class="b-remaining f-contacts-short-item__text">
                    Forplast<br/>
                    cra18 #48-02<br/>
                    Bucaramanga.<br/>
                    </div>
                </div>
                <div class="b-contacts-short-item col-md-12 col-sm-4 col-xs-12">
                    <div class="b-contacts-short-item__icon f-contacts-short-item__icon b-left f-contacts-short-item__icon_md">
                        <img src="img/facebook-logo.png" alt="">
                    </div>
                    <div class="b-remaining f-contacts-short-item__text f-contacts-short-item__text_phone">
                        <a href="https://www.facebook.com/Forplast-La-Tienda-Del-Motociclista-106869979347501/">facebook: Forplast</a>
                    </div>
                </div>
                <div class="b-contacts-short-item col-md-12 col-sm-4 col-xs-12">
                    <div class="b-contacts-short-item__icon f-contacts-short-item__icon b-left f-contacts-short-item__icon_xs">
                    <i class="fa fa-envelope"></i>
                    </div>
                    <div class="b-remaining f-contacts-short-item__text f-contacts-short-item__text_email">
                    <a href="mailto:forplastbucaramanga@hotmail.com">forplastbucaramanga@hotmail.com</a>
                    </div>
                </div>
                </div>
            </div>
    
            
        </div>
    </div>
</footer>