<head>
  <meta charset="utf-8">
  <title>hackathon</title>
    <!-- 
    <link rel="shortcut icon" href="https://cdn.sstatic.net/Sites/es/img/favicon.ico?v=a8def514be8a">

    La cual se inserta después de la etiqueta title o dentro de tu head de tu HTML. La extensión de la imagen debe de ser en .ico, hay muchos generadores de favicon online.

    Por ejemplo: https://www.favicon-generator.org/
    -->
    <link rel="shortcut icon" href="<?php echo Conectar::ruta();?>favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- bxslider -->
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/bxslider/jquery.bxslider.css">
    <!-- End bxslider -->
    <!-- flexslider -->
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/flexslider/flexslider.css">
    <!-- End flexslider -->

    <!-- bxslider -->
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/radial-progress/style.css">
    <!-- End bxslider -->

    <!-- Animate css -->
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>css/animate.css">
    <!-- End Animate css -->

    <!-- Bootstrap css -->
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>css/bootstrap.min.css">
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/bootstrap-progressbar/bootstrap-progressbar-3.2.0.min.css">
    <!-- End Bootstrap css -->

    <!-- Jquery UI css -->
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/jqueryui/jquery-ui.css">
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/jqueryui/jquery-ui.structure.css">
    <!-- End Jquery UI css -->

    <!-- Fancybox -->
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/fancybox/jquery.fancybox.css">
    <!-- End Fancybox -->

    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>fonts/fonts.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <link type="text/css" data-themecolor="default" rel='stylesheet' href="<?php echo Conectar::ruta();?>css/main-default.css">
    <link type="text/css" data-themecolor="default" rel='stylesheet' href="<?php echo Conectar::ruta();?>css/iconos.css">

    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/rs-plugin/css/settings.css">
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/rs-plugin/css/settings-custom.css">
    <link type="text/css" rel='stylesheet' href="<?php echo Conectar::ruta();?>js/rs-plugin/videojs/video-js.css">
</head>