   <header>
        <div class="container b-header__box b-relative">
          <a href="<?php echo Conectar::ruta();?>" class="b-left b-logo "><img class="color-theme" data-retina src="<?php echo Conectar::ruta();?>img/forplast-logo-header.png" alt="Logo" /></a>
            <div class="b-header-r b-right b-header-r--icon">
    
    
                    <!-- ---- botones del nav  ------------------------------------------ -->
                    
                <nav class="b-top-nav f-top-nav b-right j-top-nav">
                        <ul class="b-top-nav__1level_wrap">

                            <!-- - - - - bnt inicio - - - - -->
                            <li class="b-top-nav__1level f-top-nav__1level is-active-top-nav__1level f-primary-b">
                                <a href="<?php echo Conectar::ruta();?>"><i class="fa fa-home b-menu-1level-ico"></i>Inicio <span class="b-ico-dropdown"><i class="fa fa-arrow-circle-down"></i></span></a>
    
                            </li>
    
                            <!-- - - - - bnt nosotros - - - - -->
                            <li class="b-top-nav__1level f-top-nav__1level f-primary-b">
                                <a href="<?php echo Conectar::ruta();?>c-form-info-forplast/"><i class="fa fa-folder-open b-menu-1level-ico"></i>Quienes Somos<span class="b-ico-dropdown"><i class="fa fa-arrow-circle-down"></i></span></a>
                                <div class="b-top-nav__dropdomn">
                                    <ul class="b-top-nav__2level_wrap">
                                        <li class="b-top-nav__2level_title f-top-nav__2level_title">Nosotros</li>
                                        <li class="b-top-nav__2level f-top-nav__2level f-primary"><a href="<?php echo Conectar::ruta();?>c-form-info-forplast/"><i class="fa fa-angle-right"></i>Misión y Visión</a></li>
                                    </ul>
                                </div>
                            </li>
    
                            <!-- - - - - bnt proyecto - - - - -->
                            <li class="b-top-nav__1level f-top-nav__1level f-primary-b">
                                <a href="<?php echo Conectar::ruta();?>c-frm-proyecto/"><i class="fa fa-picture-o b-menu-1level-ico"></i>Proyecto <span class="b-ico-dropdown"><i class="fa fa-arrow-circle-down"></i></span></a>
                                <div class="b-top-nav__dropdomn">
                                    <ul class="b-top-nav__2level_wrap">
                                        <li class="b-top-nav__2level_title f-top-nav__2level_title">Proyecto formativo</li>
                                        <li class="b-top-nav__2level f-top-nav__2level f-primary"><a href="<?php echo Conectar::ruta();?>c-frm-proyecto/"><i class="fa fa-angle-right"></i>Info Proyecto</a></li>
                                        <li class="b-top-nav__2level f-top-nav__2level f-primary"><a href="<?php echo Conectar::ruta();?>c-frm-equipo-desarrollador/"><i class="fa fa-angle-right"></i>Equipo</a></li>
    
                                </div>
                            </li>
    
                            <li class="b-top-nav__1level f-top-nav__1level f-primary-b">
                               <a href="<?php echo Conectar::ruta();?>c-frm-contacto/"><i class="fa fa-picture-o b-menu-1level-ico"></i>Contactenos <span class="b-ico-dropdown"><i class="fa fa-arrow-circle-down"></i></span></a>
                          </li>
    
                            <li class="b-top-nav__1level f-top-nav__1level f-primary-b">
                                <a href="<?php echo Conectar::ruta();?>c-inicio-sesion/"><i class="fa fa-picture-o b-menu-1level-ico"></i>Inicia Sesión <span class="b-ico-dropdown"><i class="fa fa-arrow-circle-down"></i></span></a>
    
                                <!-- - - - - bnt ayuda - - - - -->
                                <li class="b-top-nav__1level f-top-nav__1level f-primary-b">
                                <a href="<?php echo Conectar::ruta();?>manual/index.html"><i class="fa fa-picture-o b-menu-1level-ico"></i><img src="<?php echo Conectar::ruta();?>img/icons/help.png" title="Ayuda" style="width: 20px; height: 20px" ><span class="b-ico-dropdown"><i class="fa fa-arrow-circle-down"></i></span></a>
                            </li>
                            </li>
                        </ul>

                          
                </nav>
          </div>
        </div>
    </header>