<!-- ---- bloque de scripts ----------------------------------------------------  -->
    <script src="<?php echo Conectar::ruta();?>js/checkbox.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/eliminar.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/breakpoints.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/jquery/jquery-1.11.1.min.js"></script>
    <!-- bootstrap -->
    <script src="<?php echo Conectar::ruta();?>js/scrollspy.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/bootstrap-progressbar/bootstrap-progressbar.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/bootstrap.min.js"></script>
    <!-- end bootstrap -->
    <script src="<?php echo Conectar::ruta();?>js/masonry.pkgd.min.js"></script>
    <script src='<?php echo Conectar::ruta();?>js/imagesloaded.pkgd.min.js'></script>
    <!-- bxslider -->
    <script src="<?php echo Conectar::ruta();?>js/bxslider/jquery.bxslider.min.js"></script>
    <!-- end bxslider -->
    <!-- flexslider -->
    <script src="<?php echo Conectar::ruta();?>js/flexslider/jquery.flexslider.js"></script>
    <!-- end flexslider -->
    <!-- smooth-scroll -->
    <script src="<?php echo Conectar::ruta();?>js/smooth-scroll/SmoothScroll.js"></script>
    <!-- end smooth-scroll -->
    <!-- carousel -->
    <script src="<?php echo Conectar::ruta();?>js/jquery.carouFredSel-6.2.1-packed.js"></script>
    <!-- end carousel -->
    <script src="<?php echo Conectar::ruta();?>js/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/rs-plugin/videojs/video.js"></script>

    <!-- jquery ui -->
    <script src="<?php echo Conectar::ruta();?>js/jqueryui/jquery-ui.js"></script>
    <!-- end jquery ui -->
    <script type="text/javascript" language="javascript"
            src="http://maps.google.com/maps/api/js?sensor=false&key=AIzaSyCfVS1-Dv9bQNOIXsQhTSvj7jaDX7Oocvs"></script>
    <!-- Modules -->
    <script src="<?php echo Conectar::ruta();?>js/modules/sliders.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/ui.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/retina.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/animate-numbers.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/parallax-effect.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/settings.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/maps-google.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/color-themes.js"></script>
    <!-- End Modules -->

    <!-- Audio player -->
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>js/audioplayer/js/jquery.jplayer.min.js"></script>
    <script type="text/javascript" src="<?php echo Conectar::ruta();?>js/audioplayer/js/jplayer.playlist.min.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/audioplayer.js"></script>
    <!-- end Audio player -->

    <!-- radial Progress -->
    <script src="<?php echo Conectar::ruta();?>js/radial-progress/jquery.easing.1.3.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/d3/3.4.13/d3.min.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/radial-progress/radialProgress.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/progressbars.js"></script>
    <!-- end Progress -->

    <!-- Google services -->
    <script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>
    <script src="js/google-chart.js"></script>
    <!-- end Google services -->
    <script src="<?php echo Conectar::ruta();?>js/j.placeholder.js"></script>

    <!-- Fancybox -->
    <script src="<?php echo Conectar::ruta();?>js/fancybox/jquery.fancybox.pack.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/fancybox/jquery.mousewheel.pack.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/fancybox/jquery.fancybox.custom.js"></script>
    <!-- End Fancybox -->
    <script src="<?php echo Conectar::ruta();?>js/user.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/timeline.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/fontawesome-markers.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/markerwithlabel.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/cookie.js"></script>
    <script src="j<?php echo Conectar::ruta();?>s/loader.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/scrollIt/scrollIt.min.js"></script>
    <script src="<?php echo Conectar::ruta();?>js/modules/navigation-slide.js"></script>
<!-- - - - - fin - - - - -->