<!DOCTYPE html>
<html>
<!--Bloque Head-->
<?php
require_once("recursos/head.phtml");
?>
<!--Fin Bloque Head-->
<body>
	<!--Bloque Header-->

	<?php 
	include("recursos/header.phtml");
	?>


	<!--Fin Bloque Header--> 
	<div class="j-menu-container"></div>

	<!-- ---- inicio body ----------------------- -->
	<br>
	<div id="regContainer" class="container">
		<div class="row">
			<div class="panel panel-primary">
				<div class="panel panel-heading">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<h1>Administrador General</h1>
						</div>
						<div class="col-md-3"></div>
					</div>
					
				</div>
				<div class="panel panel-body">
					<div class="col-md-3"></div>   
					<div class="col-md-2"><a href=""><img src="<?php echo Conectar::ruta();?>img/crearuser.png"><br><h3>Usuarios</h3></a></div>
					<div class="col-md-2"><a href=""><img src="<?php echo Conectar::ruta();?>img/creardb.png"><br><h3>Crear sistema</h3></a></div>
					<div class="col-md-2"><a href=""><img src="<?php echo Conectar::ruta();?>img/activar.png"><br><h3>Gestionar tiendas</h3></a></div>        
					<div class="col-md-3"></div>
				</div>
			</div> 
		</div> 
	</div>
	<br>
	<!-- - - - -  fin body columna - - - -->


	<!-- - - -  Inicio del Footer - - - - -->
	<?php 
	require_once("recursos/footer.phtml");
	?>
	<!-- - - ------- fin--------- - - - - -->




	<!-- - - -  scripts - - - - -->
	<?php include("recursos/scripts.phtml");?>

	<!-- - - -  fin - - - - -->

</body>
</html>

